# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

pod 'Reachability'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'Qiniu'

pod 'GPUImage'

pod 'EAIntroView'
pod 'MBProgressHUD'
pod 'pop'

pod 'YYKit'
pod 'XXNibBridge'

pod 'Realm'

pod 'Fabric'


target 'Destinesia' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Destinesia

  target 'DestinesiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
